### ISSUE TITLE
srand (time(NULL)) cause undefined behaviour 

### ISSUE THREAD

**Issue by Karnatour** [spsehavirov/arm-kit#4]
Při použití srand(time(NULL) nefunguje funkce LCD_print a buď vypíše blbosti nebo nic.

**Comment by petrmadecki** [comment]
Mělo by být vyřešeno.
Bohužel bez přímého připojení k RTC bylo potřeba funkci time() upravit pro přípravek. Při každém spuštění, tak začíná počet vždy od 0, ne od data 1. 1. 1970 (UNIX time).
V případě, že by byl přípravek stále připojen k RTC by s původní funkcí time() neměl být problém.

**Comment by Karnatour** [comment]
Také mi pak došlo, že problém není v knihovně, ale v tom jak funkce time() funguje na připravku. Naštěstí přípravek má podporu HAL kde je šikovný Random Number Generator. Tím pádem tento issue zavírám
